// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace ArchiwindRevitAddIn.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BillingPlan : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The available_credits property</summary>
        public int? AvailableCredits { get; set; }
        /// <summary>The ends_on property</summary>
        public Date? EndsOn { get; set; }
        /// <summary>The monthly_credits property</summary>
        public int? MonthlyCredits { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The next_monthly_cycle_starts_on property</summary>
        public Date? NextMonthlyCycleStartsOn { get; set; }
        /// <summary>The renewal_interval property</summary>
        public global::ArchiwindRevitAddIn.Api.Models.BillingPlan_renewal_interval? RenewalInterval { get; set; }
        /// <summary>The renews_on property</summary>
        public Date? RenewsOn { get; set; }
        /// <summary>The started_on property</summary>
        public Date? StartedOn { get; set; }
        /// <summary>The state property</summary>
        public global::ArchiwindRevitAddIn.Api.Models.BillingPlan_state? State { get; set; }
        /// <summary>The suspension_reason property</summary>
        public global::ArchiwindRevitAddIn.Api.Models.BillingPlan_suspension_reason? SuspensionReason { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::ArchiwindRevitAddIn.Api.Models.BillingPlan"/> and sets the default values.
        /// </summary>
        public BillingPlan()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ArchiwindRevitAddIn.Api.Models.BillingPlan"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ArchiwindRevitAddIn.Api.Models.BillingPlan CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::ArchiwindRevitAddIn.Api.Models.BillingPlan();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "available_credits", n => { AvailableCredits = n.GetIntValue(); } },
                { "ends_on", n => { EndsOn = n.GetDateValue(); } },
                { "monthly_credits", n => { MonthlyCredits = n.GetIntValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "next_monthly_cycle_starts_on", n => { NextMonthlyCycleStartsOn = n.GetDateValue(); } },
                { "renewal_interval", n => { RenewalInterval = n.GetEnumValue<global::ArchiwindRevitAddIn.Api.Models.BillingPlan_renewal_interval>(); } },
                { "renews_on", n => { RenewsOn = n.GetDateValue(); } },
                { "started_on", n => { StartedOn = n.GetDateValue(); } },
                { "state", n => { State = n.GetEnumValue<global::ArchiwindRevitAddIn.Api.Models.BillingPlan_state>(); } },
                { "suspension_reason", n => { SuspensionReason = n.GetEnumValue<global::ArchiwindRevitAddIn.Api.Models.BillingPlan_suspension_reason>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("available_credits", AvailableCredits);
            writer.WriteDateValue("ends_on", EndsOn);
            writer.WriteIntValue("monthly_credits", MonthlyCredits);
            writer.WriteStringValue("name", Name);
            writer.WriteDateValue("next_monthly_cycle_starts_on", NextMonthlyCycleStartsOn);
            writer.WriteEnumValue<global::ArchiwindRevitAddIn.Api.Models.BillingPlan_renewal_interval>("renewal_interval", RenewalInterval);
            writer.WriteDateValue("renews_on", RenewsOn);
            writer.WriteDateValue("started_on", StartedOn);
            writer.WriteEnumValue<global::ArchiwindRevitAddIn.Api.Models.BillingPlan_state>("state", State);
            writer.WriteEnumValue<global::ArchiwindRevitAddIn.Api.Models.BillingPlan_suspension_reason>("suspension_reason", SuspensionReason);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
