// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ArchiwindRevitAddIn.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum BillingPlan_name
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "explorer")]
        #pragma warning disable CS1591
        Explorer,
        #pragma warning restore CS1591
        [EnumMember(Value = "basic")]
        #pragma warning disable CS1591
        Basic,
        #pragma warning restore CS1591
        [EnumMember(Value = "basic_ppc")]
        #pragma warning disable CS1591
        Basic_ppc,
        #pragma warning restore CS1591
        [EnumMember(Value = "professional")]
        #pragma warning disable CS1591
        Professional,
        #pragma warning restore CS1591
        [EnumMember(Value = "enterprise")]
        #pragma warning disable CS1591
        Enterprise,
        #pragma warning restore CS1591
    }
}
