// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ArchiwindRevitAddIn.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum BillingPlan_suspension_reason
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "payment_requires_action")]
        #pragma warning disable CS1591
        Payment_requires_action,
        #pragma warning restore CS1591
        [EnumMember(Value = "payment_failed")]
        #pragma warning disable CS1591
        Payment_failed,
        #pragma warning restore CS1591
    }
}
