// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ArchiwindRevitAddIn.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CreateModelFilesParamsV1_vegetation_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "very_dense")]
        #pragma warning disable CS1591
        Very_dense,
        #pragma warning restore CS1591
        [EnumMember(Value = "dense")]
        #pragma warning disable CS1591
        Dense,
        #pragma warning restore CS1591
        [EnumMember(Value = "medium_dense")]
        #pragma warning disable CS1591
        Medium_dense,
        #pragma warning restore CS1591
        [EnumMember(Value = "low_dense")]
        #pragma warning disable CS1591
        Low_dense,
        #pragma warning restore CS1591
    }
}
