// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ArchiwindRevitAddIn.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum SimulationQuality
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "draft")]
        #pragma warning disable CS1591
        Draft,
        #pragma warning restore CS1591
        [EnumMember(Value = "detailed")]
        #pragma warning disable CS1591
        Detailed,
        #pragma warning restore CS1591
    }
}
