// <auto-generated/>
#pragma warning disable CS0618
using ArchiwindRevitAddIn.Api.V1.ModelsRequests;
using ArchiwindRevitAddIn.Api.V1.Projects;
using ArchiwindRevitAddIn.Api.V1.Simulations;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ArchiwindRevitAddIn.Api.V1
{
    /// <summary>
    /// Builds and executes requests for operations under \v1
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V1RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The models property</summary>
        public global::ArchiwindRevitAddIn.Api.V1.ModelsRequests.ModelsRequestBuilder Models
        {
            get => new global::ArchiwindRevitAddIn.Api.V1.ModelsRequests.ModelsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The projects property</summary>
        public global::ArchiwindRevitAddIn.Api.V1.Projects.ProjectsRequestBuilder Projects
        {
            get => new global::ArchiwindRevitAddIn.Api.V1.Projects.ProjectsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The simulations property</summary>
        public global::ArchiwindRevitAddIn.Api.V1.Simulations.SimulationsRequestBuilder Simulations
        {
            get => new global::ArchiwindRevitAddIn.Api.V1.Simulations.SimulationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ArchiwindRevitAddIn.Api.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ArchiwindRevitAddIn.Api.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
