// <auto-generated/>
#pragma warning disable CS0618
using ArchiwindRevitAddIn.Api.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace ArchiwindRevitAddIn.Api.V1.Projects.Item.Simulations
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\projects\{-id}\simulations
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SimulationsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::ArchiwindRevitAddIn.Api.V1.Projects.Item.Simulations.SimulationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SimulationsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/projects/{%2Did}/simulations{?limit*,offset*,status*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ArchiwindRevitAddIn.Api.V1.Projects.Item.Simulations.SimulationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SimulationsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/projects/{%2Did}/simulations{?limit*,offset*,status*}", rawUrl)
        {
        }
        /// <returns>A <see cref="global::ArchiwindRevitAddIn.Api.V1.Projects.Item.Simulations.SimulationsGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::ArchiwindRevitAddIn.Api.Models.JsonErrorResponse">When receiving a 401 status code</exception>
        /// <exception cref="global::ArchiwindRevitAddIn.Api.Models.JsonErrorResponse">When receiving a 422 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::ArchiwindRevitAddIn.Api.V1.Projects.Item.Simulations.SimulationsGetResponse?> GetAsSimulationsGetResponseAsync(Action<RequestConfiguration<global::ArchiwindRevitAddIn.Api.V1.Projects.Item.Simulations.SimulationsRequestBuilder.SimulationsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::ArchiwindRevitAddIn.Api.V1.Projects.Item.Simulations.SimulationsGetResponse> GetAsSimulationsGetResponseAsync(Action<RequestConfiguration<global::ArchiwindRevitAddIn.Api.V1.Projects.Item.Simulations.SimulationsRequestBuilder.SimulationsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::ArchiwindRevitAddIn.Api.Models.JsonErrorResponse.CreateFromDiscriminatorValue },
                { "422", global::ArchiwindRevitAddIn.Api.Models.JsonErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::ArchiwindRevitAddIn.Api.V1.Projects.Item.Simulations.SimulationsGetResponse>(requestInfo, global::ArchiwindRevitAddIn.Api.V1.Projects.Item.Simulations.SimulationsGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="global::ArchiwindRevitAddIn.Api.V1.Projects.Item.Simulations.SimulationsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::ArchiwindRevitAddIn.Api.Models.JsonErrorResponse">When receiving a 401 status code</exception>
        /// <exception cref="global::ArchiwindRevitAddIn.Api.Models.JsonErrorResponse">When receiving a 422 status code</exception>
        [Obsolete("This method is obsolete. Use GetAsSimulationsGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::ArchiwindRevitAddIn.Api.V1.Projects.Item.Simulations.SimulationsResponse?> GetAsync(Action<RequestConfiguration<global::ArchiwindRevitAddIn.Api.V1.Projects.Item.Simulations.SimulationsRequestBuilder.SimulationsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::ArchiwindRevitAddIn.Api.V1.Projects.Item.Simulations.SimulationsResponse> GetAsync(Action<RequestConfiguration<global::ArchiwindRevitAddIn.Api.V1.Projects.Item.Simulations.SimulationsRequestBuilder.SimulationsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::ArchiwindRevitAddIn.Api.Models.JsonErrorResponse.CreateFromDiscriminatorValue },
                { "422", global::ArchiwindRevitAddIn.Api.Models.JsonErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::ArchiwindRevitAddIn.Api.V1.Projects.Item.Simulations.SimulationsResponse>(requestInfo, global::ArchiwindRevitAddIn.Api.V1.Projects.Item.Simulations.SimulationsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::ArchiwindRevitAddIn.Api.V1.Projects.Item.Simulations.SimulationsRequestBuilder.SimulationsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::ArchiwindRevitAddIn.Api.V1.Projects.Item.Simulations.SimulationsRequestBuilder.SimulationsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::ArchiwindRevitAddIn.Api.V1.Projects.Item.Simulations.SimulationsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::ArchiwindRevitAddIn.Api.V1.Projects.Item.Simulations.SimulationsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::ArchiwindRevitAddIn.Api.V1.Projects.Item.Simulations.SimulationsRequestBuilder(rawUrl, RequestAdapter);
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        #pragma warning disable CS1591
        public partial class SimulationsRequestBuilderGetQueryParameters 
        #pragma warning restore CS1591
        {
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            [QueryParameter("offset")]
            public int? Offset { get; set; }
            [Obsolete("This property is deprecated, use StatusAsGetStatusQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("status")]
            public string? Status { get; set; }
#nullable restore
#else
            [QueryParameter("status")]
            public string Status { get; set; }
#endif
            [QueryParameter("status")]
            public global::ArchiwindRevitAddIn.Api.V1.Projects.Item.Simulations.GetStatusQueryParameterType? StatusAsGetStatusQueryParameterType { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class SimulationsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::ArchiwindRevitAddIn.Api.V1.Projects.Item.Simulations.SimulationsRequestBuilder.SimulationsRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
